In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv("nassau_candy_date_fixed.csv")
df.head()

               Row Labels  Average of Cost  Average of Lead time
0  Everlasting Gobstopper         8.666667            1394.666667
1          Secret Factory         8.666667            1394.666667
2    Fizzy Lifting Drinks         5.250000            1273.500000
3             Sugar Shack         5.250000            1273.500000
4                 Fun Dip         2.400000            1272.666667

In [3]:
df.columns.tolist()

['Row Labels', 'Average of Cost', 'Average of Lead time ']

In [4]:
df = pd.read_csv("Nassau_Candy_Distributor.csv")
df.columns.tolist()

FileNotFoundError: [Errno 2] No such file or directory: 'Nassau_Candy_Distributor.csv'

In [1]:
import os

print(os.getcwd())
print(os.listdir())

c:\Users\sonku\OneDrive\Desktop\Nassau Candy
['.ipynb_checkpoints', 'Nassau Candy Distributor.csv', 'nassau_factory_optimization.ipynb']

In [2]:
df = pd.read_csv("Nassau Candy Distributor.csv")
df.head()

NameError: name 'pd' is not defined

In [3]:
import pandas as pd

df = pd.read_csv("Nassau Candy Distributor.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Sales,Units,Gross Profit,Cost,Average of Lead time,Unnamed: 19,Average of Cost,Average of Lead time .1,Row Labels,lead time
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,...,6.50,2,4.22,2.28,1394.666667,NaN,8.666667,1394.666667,Everlasting Gobstopper,909.0
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,...,7.50,2,4.90,2.60,1394.666667,NaN,8.666667,1394.666667,Secret Factory,909.0
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,...,10.47,3,7.47,3.00,1273.500000,NaN,5.250000,1273.500000,Fizzy Lifting Drinks,909.0
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,...,10.80,3,7.50,3.30,1273.500000,NaN,5.250000,1273.500000,Sugar Shack,909.0
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,11.25,3,7.35,3.90,1272.666667,NaN,2.400000,1272.666667,Fun Dip,912.0

In [4]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Country/Region',
 'City',
 'State/Province',
 'Postal Code',
 'Division',
 'Region',
 'Product ID',
 'Product Name',
 'Sales',
 'Units',
 'Gross Profit',
 'Cost',
 'Average of Lead time ',
 'Unnamed: 19',
 'Average of Cost',
 'Average of Lead time .1',
 'Row Labels',
 'lead time']

In [5]:
df = df[['Row ID', 'Order ID', 'Order Date', 'Ship Date',
         'Ship Mode', 'Customer ID', 'Country/Region', 'City',
         'State/Province', 'Postal Code', 'Division', 'Region',
         'Product ID', 'Product Name', 'Sales', 'Units',
         'Gross Profit', 'Cost', 'lead time']]

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,lead time
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909.0
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909.0
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909.0
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909.0
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912.0

In [6]:
X = df[['Product Name', 'Region', 'Ship Mode']]
y = df['lead time']

print("Features:", X.columns.tolist())
print("Target:", y.name)

Features: ['Product Name', 'Region', 'Ship Mode']
Target: lead time

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features = ['Product Name', 'Region', 'Ship Mode']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

X_encoded = preprocessor.fit_transform(X)

print("Encoding complete!")
print("Encoded shape:", X_encoded.shape)

ModuleNotFoundError: No module named 'sklearn'

In [8]:
%pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.2.5)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp313-cp313-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.24.0)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 273.0 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/8.2 MB 273.0 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/8.2 MB 273.0 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/8.2 MB 273.0 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/8.2 MB 273.0 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/8.2 MB 273.0 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/8.2 MB 273.0 kB/s eta 0:00:29
   --- ------------------------------------ 0.8/8.2 MB 227.4 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/8.2 MB 227.4 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/8.2 MB 227.4 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/8.2 MB 227.4 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/8.2 MB 227.4 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/8.2 MB 227.4 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/8.2 MB 227.4 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/8.2 MB 227.4 kB/s eta 0:00:33
   ----- ---------------------------------- 1.0/8.2 MB 197.0 kB/s eta 0:00:37
   ----- ---------------------------------- 1.0/8.2 MB 197.0 kB/s eta 0:00:37
   ----- ---------------------------------- 1.0/8.2 MB 197.0 kB/s eta 0:00:37
   ------ --------------------------------- 1.3/8.2 MB 220.1 kB/s eta 0:00:32
   ------ --------------------------------- 1.3/8.2 MB 220.1 kB/s eta 0:00:32
   ------- -------------------------------- 1.6/8.2 MB 252.6 kB/s eta 0:00:27
   ------- -------------------------------- 1.6/8.2 MB 252.6 kB/s eta 0:00:27
   ------- -------------------------------- 1.6/8.2 MB 252.6 kB/s eta 0:00:27
   ------- -------------------------------- 1.6/8.2 MB 252.6 kB/s eta 0:00:27
   -------- ------------------------------- 1.8/8.2 MB 263.8 kB/s eta 0:00:25
   -------- ------------------------------- 1.8/8.2 MB 263.8 kB/s eta 0:00:25
   -------- ------------------------------- 1.8/8.2 MB 263.8 kB/s eta 0:00:25
   -------- ------------------------------- 1.8/8.2 MB 263.8 kB/s eta 0:00:25
   -------- ------------------------------- 1.8/8.2 MB 263.8 kB/s eta 0:00:25
   ---------- ----------------------------- 2.1/8.2 MB 261.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.1/8.2 MB 261.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.1/8.2 MB 261.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.1/8.2 MB 261.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.1/8.2 MB 261.0 kB/s eta 0:00:24
   ----------- ---------------------------- 2.4/8.2 MB 259.9 kB/s eta 0:00:23
   ----------- ---------------------------- 2.4/8.2 MB 259.9 kB/s eta 0:00:23
   ----------- ---------------------------- 2.4/8.2 MB 259.9 kB/s eta 0:00:23
   ------------ --------------------------- 2.6/8.2 MB 268.3 kB/s eta 0:00:21
   ------------ --------------------------- 2.6/8.2 MB 268.3 kB/s eta 0:00:21
   ------------ --------------------------- 2.6/8.2 MB 268.3 kB/s eta 0:00:21
   -------------- ------------------------- 2.9/8.2 MB 278.0 kB/s eta 0:00:20
   -------------- ------------------------- 2.9/8.2 MB 278.0 kB/s eta 0:00:20
   -------------- ------------------------- 2.9/8.2 MB 278.0 kB/s eta 0:00:20
   -------------- ------------------------- 2.9/8.2 MB 278.0 kB/s eta 0:00:20
   -------------- ------------------------- 2.9/8.2 MB 278.0 kB/s eta 0:00:20
   --------------- ------------------------ 3.1/8.2 MB 274.6 kB/s eta 0:00:19
   --------------- ------------------------ 3.1/8.2 MB 274.6 kB/s eta 0:00:19
   --------------- ------------------------ 3.1/8.2 MB 274.6 kB/s eta 0:00:19
   ---------------- ----------------------- 3.4/8.2 MB 284.6 kB/s eta 0:00:17
   ---------------- ----------------------- 3.4/8.2 MB 284.6 kB/s eta 0:00:17
   ----------------- ---------------------- 3.7/8.2 MB 297.3 kB/s eta 0:00:16
   ----------------- ---------------------- 3.7/8.2 MB 297.3 kB/s eta 0:00:16
   ----------------- ---------------------- 3.7/8.2 MB 297.3 kB/s eta 0:00:16
   ------------------- -------------------- 3.9/8.2 MB 300.4 kB/s eta 0:00:15
   ------------------- -------------------- 3.9/8.2 MB 300.4 kB/s eta 0:00:15
   ------------------- -------------------- 3.9/8.2 MB 300.4 kB/s eta 0:00:15
   ------------------- -------------------- 3.9/8.2 MB 300.4 kB/s eta 0:00:15
   ------------------- -------------------- 3.9/8.2 MB 300.4 kB/s eta 0:00:15
   ------------------- -------------------- 3.9/8.2 MB 300.4 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.2 MB 291.5 kB/s eta 0:00:14
   -------------------- ------------------- 4.2/8.2 MB 291.5 kB/s eta 0:00:14
   -------------------- ------------------- 4.2/8.2 MB 291.5 kB/s eta 0:00:14
   -------------------- ------------------- 4.2/8.2 MB 291.5 kB/s eta 0:00:14
   --------------------- ------------------ 4.5/8.2 MB 292.2 kB/s eta 0:00:13
   --------------------- ------------------ 4.5/8.2 MB 292.2 kB/s eta 0:00:13
   --------------------- ------------------ 4.5/8.2 MB 292.2 kB/s eta 0:00:13
   --------------------- ------------------ 4.5/8.2 MB 292.2 kB/s eta 0:00:13
   ----------------------- ---------------- 4.7/8.2 MB 296.3 kB/s eta 0:00:12
   ----------------------- ---------------- 4.7/8.2 MB 296.3 kB/s eta 0:00:12
   ----------------------- ---------------- 4.7/8.2 MB 296.3 kB/s eta 0:00:12
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 300.0 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 276.9 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 276.9 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 276.9 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 276.9 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 276.9 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 276.9 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 276.9 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.2 MB 276.9 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.2 MB 267.6 kB/s eta 0:00:11
   ---------------------------- ----------- 5.8/8.2 MB 251.1 kB/s eta 0:00:10
   ---------------------------- ----------- 5.8/8.2 MB 251.1 kB/s eta 0:00:10
   ---------------------------- ----------- 5.8/8.2 MB 251.1 kB/s eta 0:00:10
   ---------------------------- ----------- 5.8/8.2 MB 251.1 kB/s eta 0:00:10
   ---------------------------- ----------- 5.8/8.2 MB 251.1 kB/s eta 0:00:10
   ---------------------------- ----------- 5.8/8.2 MB 251.1 kB/s eta 0:00:10
   ---------------------------- ----------- 5.8/8.2 MB 251.1 kB/s eta 0:00:10
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.2 MB 245.4 kB/s eta 0:00:09
   ------------------------------ --------- 6.3/8.2 MB 234.1 kB/s eta 0:00:09
   ------------------------------ --------- 6.3/8.2 MB 234.1 kB/s eta 0:00:09
   ------------------------------ --------- 6.3/8.2 MB 234.1 kB/s eta 0:00:09
   ------------------------------ --------- 6.3/8.2 MB 234.1 kB/s eta 0:00:09
   ------------------------------ --------- 6.3/8.2 MB 234.1 kB/s eta 0:00:09
   ------------------------------ --------- 6.3/8.2 MB 234.1 kB/s eta 0:00:09
   ------------------------------ --------- 6.3/8.2 MB 234.1 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.2 MB 231.5 kB/s eta 0:00:08
   -------------------------------- ------- 6.6/8.2 MB 231.5 kB/s eta 0:00:08
   -------------------------------- ------- 6.6/8.2 MB 231.5 kB/s eta 0:00:08
   -------------------------------- ------- 6.6/8.2 MB 231.5 kB/s eta 0:00:08
   -------------------------------- ------- 6.6/8.2 MB 231.5 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.2 MB 231.8 kB/s eta 0:00:06
   --------------------------------- ------ 6.8/8.2 MB 231.8 kB/s eta 0:00:06
   --------------------------------- ------ 6.8/8.2 MB 231.8 kB/s eta 0:00:06
   ---------------------------------- ----- 7.1/8.2 MB 236.0 kB/s eta 0:00:05
   ---------------------------------- ----- 7.1/8.2 MB 236.0 kB/s eta 0:00:05
   ----------------------------------- ---- 7.3/8.2 MB 240.8 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 240.8 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 240.8 kB/s eta 0:00:04
   ------------------------------------- -- 7.6/8.2 MB 245.0 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 245.0 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.2 MB 245.0 kB/s eta 0:00:03
   -------------------------------------- - 7.9/8.2 MB 247.9 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 247.9 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 247.9 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 247.9 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 247.9 kB/s eta 0:00:02
   ---------------------------------------  8.1/8.2 MB 250.6 kB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 250.6 kB/s eta 0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.18.0-cp313-cp313-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
    --------------------------------------- 0.5/36.6 MB 247.0 kB/s eta 0:02:26
    --------------------------------------- 0.5/36.6 MB 247.0 kB/s eta 0:02:26
    --------------------------------------- 0.5/36.6 MB 247.0 kB/s eta 0:02:26
    --------------------------------------- 0.5/36.6 MB 247.0 kB/s eta 0:02:26
    --------------------------------------- 0.5/36.6 MB 247.0 kB/s eta 0:02:26
    --------------------------------------- 0.8/36.6 MB 240.6 kB/s eta 0:02:29
    --------------------------------------- 0.8/36.6 MB 240.6 kB/s eta 0:02:29
    --------------------------------------- 0.8/36.6 MB 240.6 kB/s eta 0:02:29
   - -------------------------------------- 1.0/36.6 MB 289.9 kB/s eta 0:02:03
   - -------------------------------------- 1.0/36.6 MB 289.9 kB/s eta 0:02:03
   - -------------------------------------- 1.0/36.6 MB 289.9 kB/s eta 0:02:03
   - -------------------------------------- 1.3/36.6 MB 303.1 kB/s eta 0:01:57
   - -------------------------------------- 1.3/36.6 MB 303.1 kB/s eta 0:01:57
   - -------------------------------------- 1.3/36.6 MB 303.1 kB/s eta 0:01:57
   - -------------------------------------- 1.3/36.6 MB 303.1 kB/s eta 0:01:57
   - -------------------------------------- 1.6/36.6 MB 309.7 kB/s eta 0:01:53
   - -------------------------------------- 1.6/36.6 MB 309.7 kB/s eta 0:01:53
   - -------------------------------------- 1.6/36.6 MB 309.7 kB/s eta 0:01:53
   - -------------------------------------- 1.6/36.6 MB 309.7 kB/s eta 0:01:53
   - -------------------------------------- 1.6/36.6 MB 309.7 kB/s eta 0:01:53
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.8/36.6 MB 290.7 kB/s eta 0:02:00
   -- ------------------------------------- 2.1/36.6 MB 249.7 kB/s eta 0:02:18
   -- ------------------------------------- 2.1/36.6 MB 249.7 kB/s eta 0:02:18
   -- ------------------------------------- 2.1/36.6 MB 249.7 kB/s eta 0:02:18
   -- ------------------------------------- 2.1/36.6 MB 249.7 kB/s eta 0:02:18
   -- ------------------------------------- 2.4/36.6 MB 254.5 kB/s eta 0:02:15
   -- ------------------------------------- 2.4/36.6 MB 254.5 kB/s eta 0:02:15
   -- ------------------------------------- 2.4/36.6 MB 254.5 kB/s eta 0:02:15
   -- ------------------------------------- 2.4/36.6 MB 254.5 kB/s eta 0:02:15
   -- ------------------------------------- 2.4/36.6 MB 254.5 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   -- ------------------------------------- 2.6/36.6 MB 252.7 kB/s eta 0:02:15
   --- ------------------------------------ 2.9/36.6 MB 229.4 kB/s eta 0:02:27
   --- ------------------------------------ 2.9/36.6 MB 229.4 kB/s eta 0:02:27
   --- ------------------------------------ 2.9/36.6 MB 229.4 kB/s eta 0:02:27
   --- ------------------------------------ 2.9/36.6 MB 229.4 kB/s eta 0:02:27
   --- ------------------------------------ 2.9/36.6 MB 229.4 kB/s eta 0:02:27
   --- ------------------------------------ 3.1/36.6 MB 230.7 kB/s eta 0:02:25
   --- ------------------------------------ 3.1/36.6 MB 230.7 kB/s eta 0:02:25
   --- ------------------------------------ 3.1/36.6 MB 230.7 kB/s eta 0:02:25
   --- ------------------------------------ 3.4/36.6 MB 240.9 kB/s eta 0:02:18
   --- ------------------------------------ 3.4/36.6 MB 240.9 kB/s eta 0:02:18
   --- ------------------------------------ 3.4/36.6 MB 240.9 kB/s eta 0:02:18
   ---- ----------------------------------- 3.7/36.6 MB 246.0 kB/s eta 0:02:14
   ---- ----------------------------------- 3.7/36.6 MB 246.0 kB/s eta 0:02:14
   ---- ----------------------------------- 3.7/36.6 MB 246.0 kB/s eta 0:02:14
   ---- ----------------------------------- 3.9/36.6 MB 254.9 kB/s eta 0:02:08
   ---- ----------------------------------- 3.9/36.6 MB 254.9 kB/s eta 0:02:08
   ---- ----------------------------------- 4.2/36.6 MB 267.0 kB/s eta 0:02:02
   ---- ----------------------------------- 4.2/36.6 MB 267.0 kB/s eta 0:02:02
   ---- ----------------------------------- 4.5/36.6 MB 274.7 kB/s eta 0:01:57
   ---- ----------------------------------- 4.5/36.6 MB 274.7 kB/s eta 0:01:57
   ---- ----------------------------------- 4.5/36.6 MB 274.7 kB/s eta 0:01:57
   ---- ----------------------------------- 4.5/36.6 MB 274.7 kB/s eta 0:01:57
   ----- ---------------------------------- 4.7/36.6 MB 277.3 kB/s eta 0:01:55
   ----- ---------------------------------- 4.7/36.6 MB 277.3 kB/s eta 0:01:55
   ----- ---------------------------------- 5.0/36.6 MB 284.2 kB/s eta 0:01:52
   ----- ---------------------------------- 5.0/36.6 MB 284.2 kB/s eta 0:01:52
   ----- ---------------------------------- 5.2/36.6 MB 294.1 kB/s eta 0:01:47
   ----- ---------------------------------- 5.2/36.6 MB 294.1 kB/s eta 0:01:47
   ------ --------------------------------- 5.5/36.6 MB 301.8 kB/s eta 0:01:43
   ------ --------------------------------- 5.8/36.6 MB 312.8 kB/s eta 0:01:39
   ------ --------------------------------- 6.0/36.6 MB 324.2 kB/s eta 0:01:35
   ------ --------------------------------- 6.0/36.6 MB 324.2 kB/s eta 0:01:35
   ------ --------------------------------- 6.3/36.6 MB 331.7 kB/s eta 0:01:32

WARNING: Ignoring invalid distribution ~ip (C:\Users\sonku\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\sonku\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\sonku\AppData\Roaming\Python\Python313\site-packages)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features = ['Product Name', 'Region', 'Ship Mode']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

X_encoded = preprocessor.fit_transform(X)

print("Encoding complete!")
print("Encoded shape:", X_encoded.shape)

Encoding complete!
Encoded shape: (10194, 23)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])

Training rows: 8155
Testing rows: 2039

In [11]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

print("Linear Regression complete!")

ValueError: Input y contains NaN.

In [12]:
df['lead time'].isna().sum()

np.int64(10163)

In [13]:
df_model = df.dropna(subset=['lead time']).copy()

X = df_model[['Product Name', 'Region', 'Ship Mode']]
y = df_model['lead time']

print("Remaining rows:", len(df_model))
print("Missing Lead Time:", y.isna().sum())

Remaining rows: 31
Missing Lead Time: 0

In [14]:
df.shape

(10194, 19)

In [15]:
df['lead time'].value_counts(dropna=False).head(10)

lead time
NaN      10163
909.0       13
910.0        9
907.0        5
908.0        2
906.0        1
912.0        1
Name: count, dtype: int64

In [16]:
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True, errors='coerce')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True, errors='coerce')

df['lead time'] = (df['Ship Date'] - df['Order Date']).dt.days

print(df['lead time'].isna().sum())
print(df['lead time'].describe())

0
count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: lead time, dtype: float64

In [17]:
X = df[['Product Name', 'Region', 'Ship Mode']]
y = df['lead time']

print(X.shape)
print(y.shape)

(10194, 3)
(10194,)

In [18]:
X_encoded = preprocessor.fit_transform(X)

print("Encoding complete!")
print("Shape:", X_encoded.shape)

Encoding complete!
Shape: (10194, 23)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)

print("Training:", X_train.shape[0])
print("Testing:", X_test.shape[0])

Training: 8155
Testing: 2039

In [20]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

print("Linear Regression complete!")

Linear Regression complete!

In [21]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

rmse = np.sqrt(mean_squared_error(y_test, lr_pred))
mae = mean_absolute_error(y_test, lr_pred)
r2 = r2_score(y_test, lr_pred)

print("RMSE:", rmse)
print("MAE:", mae)
print("R²:", r2)

RMSE: 266.6701212262439
MAE: 215.27970349296885
R²: -0.00554667513022733

In [22]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Random Forest complete!")

Random Forest complete!

In [23]:
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
rf_mae = mean_absolute_error(y_test, rf_pred)
rf_r2 = r2_score(y_test, rf_pred)

print("RMSE:", rf_rmse)
print("MAE:", rf_mae)
print("R²:", rf_r2)

RMSE: 267.6907063592071
MAE: 215.24373452080275
R²: -0.013258148604196274

In [24]:
from sklearn.ensemble import GradientBoostingRegressor

gb_model = GradientBoostingRegressor(random_state=42)

gb_model.fit(X_train, y_train)

gb_pred = gb_model.predict(X_test)

print("Gradient Boosting complete!")

Gradient Boosting complete!

In [25]:
gb_rmse = np.sqrt(mean_squared_error(y_test, gb_pred))
gb_mae = mean_absolute_error(y_test, gb_pred)
gb_r2 = r2_score(y_test, gb_pred)

print("RMSE:", gb_rmse)
print("MAE:", gb_mae)
print("R²:", gb_r2)

RMSE: 266.9841196106764
MAE: 215.34091605714758
R²: -0.007916088835734136

In [26]:
factory_map = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",
    "Everlasting Gobstopper": "Secret Factory",
    "Hair Toffee": "The Other Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",
    "Kazookles": "The Other Factory"
}

df["Current Factory"] = df["Product Name"].map(factory_map)

print("Missing Factory:", df["Current Factory"].isna().sum())

Missing Factory: 0

In [27]:
X = df[['Product Name', 'Current Factory', 'Region', 'Ship Mode']]
y = df['lead time']

categorical_features = ['Product Name', 'Current Factory', 'Region', 'Ship Mode']

preprocessor_factory = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

X_encoded_factory = preprocessor_factory.fit_transform(X)

print("Factory feature added!")
print(X_encoded_factory.shape)

Factory feature added!
(10194, 28)

In [28]:
X_train_f, X_test_f, y_train_f, y_test_f = train_test_split(
    X_encoded_factory, y, test_size=0.2, random_state=42
)

rf_factory = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_factory.fit(X_train_f, y_train_f)

rf_factory_pred = rf_factory.predict(X_test_f)

print("Factory-aware model complete!")

Factory-aware model complete!

In [29]:
factories = [
    "Lot's O' Nuts",
    "Wicked Choccy's",
    "Sugar Shack",
    "Secret Factory",
    "The Other Factory"
]

scenario_rows = []

for product in df["Product Name"].unique():
    product_data = df[df["Product Name"] == product].iloc[0]

    for factory in factories:
        scenario_rows.append({
            "Product Name": product,
            "Current Factory": product_data["Current Factory"],
            "Scenario Factory": factory,
            "Region": product_data["Region"],
            "Ship Mode": product_data["Ship Mode"]
        })

scenario_df = pd.DataFrame(scenario_rows)

print("Scenarios created:", len(scenario_df))
scenario_df.head()

Scenarios created: 75

,Product Name,Current Factory,Scenario Factory,Region,Ship Mode
0,Wonka Bar - Milk Chocolate,Wicked Choccy's,Lot's O' Nuts,Interior,Standard Class
1,Wonka Bar - Milk Chocolate,Wicked Choccy's,Wicked Choccy's,Interior,Standard Class
2,Wonka Bar - Milk Chocolate,Wicked Choccy's,Sugar Shack,Interior,Standard Class
3,Wonka Bar - Milk Chocolate,Wicked Choccy's,Secret Factory,Interior,Standard Class
4,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,Interior,Standard Class

In [30]:
X_scenario = scenario_df[
    ['Product Name', 'Scenario Factory', 'Region', 'Ship Mode']
].copy()

X_scenario = X_scenario.rename(
    columns={'Scenario Factory': 'Current Factory'}
)

X_scenario_encoded = preprocessor_factory.transform(X_scenario)

scenario_df["Predicted Lead Time"] = rf_factory.predict(X_scenario_encoded)

scenario_df.head()

,Product Name,Current Factory,Scenario Factory,Region,Ship Mode,Predicted Lead Time
0,Wonka Bar - Milk Chocolate,Wicked Choccy's,Lot's O' Nuts,Interior,Standard Class,1332.493569
1,Wonka Bar - Milk Chocolate,Wicked Choccy's,Wicked Choccy's,Interior,Standard Class,1326.723895
2,Wonka Bar - Milk Chocolate,Wicked Choccy's,Sugar Shack,Interior,Standard Class,1399.315829
3,Wonka Bar - Milk Chocolate,Wicked Choccy's,Secret Factory,Interior,Standard Class,1306.317771
4,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,Interior,Standard Class,1289.242656

In [31]:
X_scenario = scenario_df[
    ['Product Name', 'Scenario Factory', 'Region', 'Ship Mode']
].copy()

X_scenario = X_scenario.rename(
    columns={'Scenario Factory': 'Current Factory'}
)

X_scenario_encoded = preprocessor_factory.transform(X_scenario)

scenario_df["Predicted Lead Time"] = rf_factory.predict(X_scenario_encoded)

scenario_df.head()

,Product Name,Current Factory,Scenario Factory,Region,Ship Mode,Predicted Lead Time
0,Wonka Bar - Milk Chocolate,Wicked Choccy's,Lot's O' Nuts,Interior,Standard Class,1332.493569
1,Wonka Bar - Milk Chocolate,Wicked Choccy's,Wicked Choccy's,Interior,Standard Class,1326.723895
2,Wonka Bar - Milk Chocolate,Wicked Choccy's,Sugar Shack,Interior,Standard Class,1399.315829
3,Wonka Bar - Milk Chocolate,Wicked Choccy's,Secret Factory,Interior,Standard Class,1306.317771
4,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,Interior,Standard Class,1289.242656

In [32]:
current_lead = (
    df.groupby("Product Name")["lead time"]
    .mean()
    .reset_index()
    .rename(columns={"lead time": "Current Lead Time"})
)

recommendations = scenario_df.merge(
    current_lead,
    on="Product Name",
    how="left"
)

recommendations["Lead Time Reduction"] = (
    recommendations["Current Lead Time"]
    - recommendations["Predicted Lead Time"]
)

recommendations["Lead Time Reduction %"] = (
    recommendations["Lead Time Reduction"]
    / recommendations["Current Lead Time"]
) * 100

best_factory = (
    recommendations
    .sort_values(["Product Name", "Predicted Lead Time"])
    .groupby("Product Name")
    .first()
    .reset_index()
)

best_factory[
    ["Product Name", "Current Factory", "Scenario Factory",
     "Current Lead Time", "Predicted Lead Time",
     "Lead Time Reduction %"]
]

,Product Name,Current Factory,Scenario Factory,Current Lead Time,Predicted Lead Time,Lead Time Reduction %
0,Everlasting Gobstopper,Secret Factory,Sugar Shack,1394.666667,1213.078065,13.020215
1,Fizzy Lifting Drinks,Sugar Shack,Sugar Shack,1273.500000,1087.467189,14.607995
2,Fun Dip,Sugar Shack,The Other Factory,1272.666667,1199.136434,5.777651
3,Hair Toffee,The Other Factory,Secret Factory,1455.250000,1300.015570,10.667200
4,Kazookles,The Other Factory,The Other Factory,1272.989583,1159.579771,8.908935
5,Laffy Taffy,Sugar Shack,Sugar Shack,1383.100000,1095.569808,20.788822
6,Lickable Wallpaper,Secret Factory,Secret Factory,1339.138298,1177.813175,12.046935
7,Nerds,Sugar Shack,Sugar Shack,1274.000000,951.548966,25.310128
8,SweeTARTS,Sugar Shack,Sugar Shack,1383.500000,1161.349712,16.057122
9,Wonka Bar - Fudge Mallows,Lot's O' Nuts,Sugar Shack,1314.242024,1200.422673,8.660456
10,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,1316.764623,1289.242656,2.090121
11,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,The Other Factory,1328.915470,1283.341973,3.429375
12,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,The Other Factory,1325.661042,1265.667794,4.525534
13,Wonka Bar -Scrumdiddlyumptious,Lot's O' Nuts,The Other Factory,1320.641957,1294.125852,2.007819
14,Wonka Gum,Secret Factory,Sugar Shack,1306.525000,1203.767704,7.864931

In [33]:
best_factory.to_csv("factory_recommendations.csv", index=False)

print("Recommendation file saved!")

Recommendation file saved!

In [34]:
best_factory[
    ["Product Name",
     "Current Factory",
     "Scenario Factory",
     "Current Lead Time",
     "Predicted Lead Time",
     "Lead Time Reduction %"]
]

,Product Name,Current Factory,Scenario Factory,Current Lead Time,Predicted Lead Time,Lead Time Reduction %
0,Everlasting Gobstopper,Secret Factory,Sugar Shack,1394.666667,1213.078065,13.020215
1,Fizzy Lifting Drinks,Sugar Shack,Sugar Shack,1273.500000,1087.467189,14.607995
2,Fun Dip,Sugar Shack,The Other Factory,1272.666667,1199.136434,5.777651
3,Hair Toffee,The Other Factory,Secret Factory,1455.250000,1300.015570,10.667200
4,Kazookles,The Other Factory,The Other Factory,1272.989583,1159.579771,8.908935
5,Laffy Taffy,Sugar Shack,Sugar Shack,1383.100000,1095.569808,20.788822
6,Lickable Wallpaper,Secret Factory,Secret Factory,1339.138298,1177.813175,12.046935
7,Nerds,Sugar Shack,Sugar Shack,1274.000000,951.548966,25.310128
8,SweeTARTS,Sugar Shack,Sugar Shack,1383.500000,1161.349712,16.057122
9,Wonka Bar - Fudge Mallows,Lot's O' Nuts,Sugar Shack,1314.242024,1200.422673,8.660456
10,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,1316.764623,1289.242656,2.090121
11,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,The Other Factory,1328.915470,1283.341973,3.429375
12,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,The Other Factory,1325.661042,1265.667794,4.525534
13,Wonka Bar -Scrumdiddlyumptious,Lot's O' Nuts,The Other Factory,1320.641957,1294.125852,2.007819
14,Wonka Gum,Secret Factory,Sugar Shack,1306.525000,1203.767704,7.864931

In [35]:
factory_coords = {
    "Lot's O' Nuts": (32.881893, -111.768036),
    "Wicked Choccy's": (32.076176, -81.088371),
    "Sugar Shack": (48.119140, -96.181150),
    "Secret Factory": (41.446333, -90.565487),
    "The Other Factory": (35.117500, -89.971107)
}

print(factory_coords)

{"Lot's O' Nuts": (32.881893, -111.768036), "Wicked Choccy's": (32.076176, -81.088371), 'Sugar Shack': (48.11914, -96.18115), 'Secret Factory': (41.446333, -90.565487), 'The Other Factory': (35.1175, -89.971107)}

In [36]:
X = df[['Product Name', 'Current Factory', 'Region', 'Ship Mode']]
y = df['lead time']

X_encoded_factory = preprocessor_factory.fit_transform(X)

X_train_f, X_test_f, y_train_f, y_test_f = train_test_split(
    X_encoded_factory, y, test_size=0.2, random_state=42
)

rf_factory = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_factory.fit(X_train_f, y_train_f)

print("Final factory model trained!")

Final factory model trained!

In [37]:
X_scenario = scenario_df[
    ['Product Name', 'Scenario Factory', 'Region', 'Ship Mode']
].copy()

X_scenario = X_scenario.rename(
    columns={'Scenario Factory': 'Current Factory'}
)

X_scenario_encoded = preprocessor_factory.transform(X_scenario)

scenario_df["Predicted Lead Time"] = rf_factory.predict(X_scenario_encoded)

scenario_df.head()

,Product Name,Current Factory,Scenario Factory,Region,Ship Mode,Predicted Lead Time
0,Wonka Bar - Milk Chocolate,Wicked Choccy's,Lot's O' Nuts,Interior,Standard Class,1332.493569
1,Wonka Bar - Milk Chocolate,Wicked Choccy's,Wicked Choccy's,Interior,Standard Class,1326.723895
2,Wonka Bar - Milk Chocolate,Wicked Choccy's,Sugar Shack,Interior,Standard Class,1399.315829
3,Wonka Bar - Milk Chocolate,Wicked Choccy's,Secret Factory,Interior,Standard Class,1306.317771
4,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,Interior,Standard Class,1289.242656

In [38]:
current_lead = (
    df.groupby("Product Name")["lead time"]
    .mean()
    .reset_index()
    .rename(columns={"lead time": "Current Lead Time"})
)

recommendations = scenario_df.merge(
    current_lead,
    on="Product Name",
    how="left"
)

recommendations["Lead Time Reduction"] = (
    recommendations["Current Lead Time"]
    - recommendations["Predicted Lead Time"]
)

recommendations["Lead Time Reduction %"] = (
    recommendations["Lead Time Reduction"]
    / recommendations["Current Lead Time"]
) * 100

best_factory = (
    recommendations
    .sort_values(["Product Name", "Predicted Lead Time"])
    .groupby("Product Name")
    .first()
    .reset_index()
)

best_factory[
    ["Product Name", "Current Factory", "Scenario Factory",
     "Current Lead Time", "Predicted Lead Time",
     "Lead Time Reduction %"]
]

,Product Name,Current Factory,Scenario Factory,Current Lead Time,Predicted Lead Time,Lead Time Reduction %
0,Everlasting Gobstopper,Secret Factory,Sugar Shack,1394.666667,1213.078065,13.020215
1,Fizzy Lifting Drinks,Sugar Shack,Sugar Shack,1273.500000,1087.467189,14.607995
2,Fun Dip,Sugar Shack,The Other Factory,1272.666667,1199.136434,5.777651
3,Hair Toffee,The Other Factory,Secret Factory,1455.250000,1300.015570,10.667200
4,Kazookles,The Other Factory,The Other Factory,1272.989583,1159.579771,8.908935
5,Laffy Taffy,Sugar Shack,Sugar Shack,1383.100000,1095.569808,20.788822
6,Lickable Wallpaper,Secret Factory,Secret Factory,1339.138298,1177.813175,12.046935
7,Nerds,Sugar Shack,Sugar Shack,1274.000000,951.548966,25.310128
8,SweeTARTS,Sugar Shack,Sugar Shack,1383.500000,1161.349712,16.057122
9,Wonka Bar - Fudge Mallows,Lot's O' Nuts,Sugar Shack,1314.242024,1200.422673,8.660456
10,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,1316.764623,1289.242656,2.090121
11,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,The Other Factory,1328.915470,1283.341973,3.429375
12,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,The Other Factory,1325.661042,1265.667794,4.525534
13,Wonka Bar -Scrumdiddlyumptious,Lot's O' Nuts,The Other Factory,1320.641957,1294.125852,2.007819
14,Wonka Gum,Secret Factory,Sugar Shack,1306.525000,1203.767704,7.864931

In [39]:
factory_cost = (
    df.groupby("Current Factory")["Cost"]
    .mean()
    .reset_index()
    .sort_values("Cost", ascending=False)
)

factory_cost

     Current Factory       Cost
1     Secret Factory  19.552074
3  The Other Factory  11.300000
4    Wicked Choccy's   4.648165
0      Lot's O' Nuts   4.140741
2        Sugar Shack   3.022727

In [40]:
product_lead = (
    df.groupby("Product Name")["lead time"]
    .mean()
    .reset_index()
    .sort_values("lead time", ascending=False)
)

product_lead

                         Product Name    lead time
3                         Hair Toffee  1455.250000
0              Everlasting Gobstopper  1394.666667
8                           SweeTARTS  1383.500000
5                         Laffy Taffy  1383.100000
6                  Lickable Wallpaper  1339.138298
11  Wonka Bar - Nutty Crunch Surprise  1328.915470
12  Wonka Bar - Triple Dazzle Caramel  1325.661042
13     Wonka Bar -Scrumdiddlyumptious  1320.641957
10         Wonka Bar - Milk Chocolate  1316.764623
9           Wonka Bar - Fudge Mallows  1314.242024
14                          Wonka Gum  1306.525000
7                               Nerds  1274.000000
1                Fizzy Lifting Drinks  1273.500000
4                           Kazookles  1272.989583
2                             Fun Dip  1272.666667

In [41]:
rec_chart = best_factory[
    ["Product Name", "Lead Time Reduction %"]
].sort_values("Lead Time Reduction %", ascending=False)

rec_chart

                         Product Name  Lead Time Reduction %
7                               Nerds              25.310128
5                         Laffy Taffy              20.788822
8                           SweeTARTS              16.057122
1                Fizzy Lifting Drinks              14.607995
0              Everlasting Gobstopper              13.020215
6                  Lickable Wallpaper              12.046935
3                         Hair Toffee              10.667200
4                           Kazookles               8.908935
9           Wonka Bar - Fudge Mallows               8.660456
14                          Wonka Gum               7.864931
2                             Fun Dip               5.777651
12  Wonka Bar - Triple Dazzle Caramel               4.525534
11  Wonka Bar - Nutty Crunch Surprise               3.429375
10         Wonka Bar - Milk Chocolate               2.090121
13     Wonka Bar -Scrumdiddlyumptious               2.007819

In [1]:
df.to_csv("nassau_final.csv", index=False)
print("Saved:", df.shape)

NameError: name 'df' is not defined

In [2]:
import pandas as pd

df = pd.read_csv("Nassau Candy Distributor.csv")

print(df.shape)
print(df.columns.tolist())

(10194, 24)
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost', 'Average of Lead time ', 'Unnamed: 19', 'Average of Cost', 'Average of Lead time .1', 'Row Labels', 'lead time']

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Row ID                   10194 non-null  int64
 1   Order ID                 10194 non-null  object
 2   Order Date               10194 non-null  object
 3   Ship Date                10194 non-null  object
 4   Ship Mode                10194 non-null  object
 5   Customer ID              10194 non-null  int64
 6   Country/Region           10194 non-null  object
 7   City                     10194 non-null  object
 8   State/Province           10194 non-null  object
 9   Postal Code              10194 non-null  object
 10  Division                 10194 non-null  object
 11  Region                   10194 non-null  object
 12  Product ID               10194 non-null  object
 13  Product Name             10194 non-null  object
 14  Sales                    10194 non-null  float64
 15  Units                    10194 non-null  int64
 16  Gross Profit             10194 non-null  float64
 17  Cost                     10194 non-null  float64
 18  Average of Lead time     31 non-null     float64
 19  Unnamed: 19              0 non-null      float64
 20  Average of Cost          31 non-null     float64
 21  Average of Lead time .1  31 non-null     float64
 22  Row Labels               31 non-null     object
 23  lead time                31 non-null     float64
dtypes: float64(8), int64(3), object(13)
memory usage: 1.9+ MB

In [4]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost', 'Average of Lead time ', 'Unnamed: 19', 'Average of Cost', 'Average of Lead time .1', 'Row Labels', 'lead time']

In [5]:
# Check current dataset
print(df.shape)
print(df.columns.tolist())

(10194, 24)
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost', 'Average of Lead time ', 'Unnamed: 19', 'Average of Cost', 'Average of Lead time .1', 'Row Labels', 'lead time']

In [6]:
df = df.drop(columns=[
    'Average of Lead time ',
    'Unnamed: 19',
    'Average of Cost',
    'Average of Lead time .1',
    'Row Labels',
    'lead time'
])

In [7]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

ValueError: time data "13-01-2024" doesn't match format "%m-%d-%Y", at position 8. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [8]:
df['Order Date'] = pd.to_datetime(
    df['Order Date'], dayfirst=True, errors='coerce'
)

df['Ship Date'] = pd.to_datetime(
    df['Ship Date'], dayfirst=True, errors='coerce'
)

df['Lead Time'] = (df['Ship Date'] - df['Order Date']).dt.days

print(df[['Order Date', 'Ship Date', 'Lead Time']].head())
print("Missing Lead Time:", df['Lead Time'].isna().sum())

  Order Date  Ship Date  Lead Time
0 2024-01-03 2026-06-30        909
1 2024-01-04 2026-07-01        909
2 2024-01-04 2026-07-01        909
3 2024-01-04 2026-07-01        909
4 2024-01-05 2026-07-05        912
Missing Lead Time: 0

In [9]:
print(df['Product Name'].unique())

['Wonka Bar - Milk Chocolate' 'Wonka Bar - Triple Dazzle Caramel'
 'Wonka Bar - Nutty Crunch Surprise' 'Wonka Bar -Scrumdiddlyumptious'
 'Wonka Bar - Fudge Mallows' 'Wonka Gum' 'Kazookles' 'Lickable Wallpaper'
 'Fizzy Lifting Drinks' 'Laffy Taffy' 'SweeTARTS' 'Nerds' 'Hair Toffee'
 'Everlasting Gobstopper' 'Fun Dip']

In [10]:
factory_mapping = {
    'Wonka Bar - Milk Chocolate': "Lot's O' Nuts",
    'Wonka Bar - Triple Dazzle Caramel': "Lot's O' Nuts",
    'Wonka Bar - Nutty Crunch Surprise': "Lot's O' Nuts",
    'Wonka Bar -Scrumdiddlyumptious': "Wicked Choccy's",
    'Wonka Bar - Fudge Mallows': "Wicked Choccy's",
    'Wonka Gum': "Secret Factory",
    'Kazookles': "The Other Factory",
    'Lickable Wallpaper': "Secret Factory",
    'Fizzy Lifting Drinks': "Sugar Shack",
    'Laffy Taffy': "Sugar Shack",
    'SweeTARTS': "Sugar Shack",
    'Nerds': "Sugar Shack",
    'Hair Toffee': "The Other Factory",
    'Everlasting Gobstopper': "Secret Factory",
    'Fun Dip': "Sugar Shack"
}

df['Current Factory'] = df['Product Name'].map(factory_mapping)

print(df[['Product Name', 'Current Factory']].drop_duplicates())
print("Unmapped products:", df['Current Factory'].isna().sum())

                           Product Name    Current Factory
0            Wonka Bar - Milk Chocolate      Lot's O' Nuts
1     Wonka Bar - Triple Dazzle Caramel      Lot's O' Nuts
2     Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts
3        Wonka Bar -Scrumdiddlyumptious    Wicked Choccy's
13            Wonka Bar - Fudge Mallows    Wicked Choccy's
19                            Wonka Gum     Secret Factory
26                            Kazookles  The Other Factory
136                  Lickable Wallpaper     Secret Factory
191                Fizzy Lifting Drinks        Sugar Shack
226                         Laffy Taffy        Sugar Shack
973                           SweeTARTS        Sugar Shack
1490                              Nerds        Sugar Shack
4435                        Hair Toffee  The Other Factory
4729             Everlasting Gobstopper     Secret Factory
5007                            Fun Dip        Sugar Shack
Unmapped products: 0

In [11]:
# Final dataset save
df.to_csv("nassau_final.csv", index=False)

print("Saved successfully!")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Saved successfully!
Shape: (10194, 20)
Columns: ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost', 'Lead Time', 'Current Factory']

In [12]:
!pip install streamlit

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: streamlit in c:\users\sonku\appdata\roaming\python\python313\site-packages (1.60.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (3.1.57)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (2.2.5)
Requirement already satisfied: packaging>=20 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (11.0.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (7.35.1)
Requirement already satisfied: pyarrow<25,>=7.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (4.13.2)
Requirement already satisfied: starlette<2,>=0.40.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn<1,>=0.30.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (0.52.0)
Requirement already satisfied: httptools<1,>=0.6.3 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (4.9.0)
Requirement already satisfied: python-multipart<1,>=0.0.10 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (16.1.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.24.0)
Requirement already satisfied: idna>=2.8 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from anyio<5,>=4.0.0->streamlit) (3.10)
Requirement already satisfied: sniffio>=1.1 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from anyio<5,>=4.0.0->streamlit) (1.3.1)
Requirement already satisfied: colorama in c:\users\sonku\appdata\roaming\python\python313\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from pandas<4,>=1.4.0->streamlit) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from requests<3,>=2.27->streamlit) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from requests<3,>=2.27->streamlit) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from requests<3,>=2.27->streamlit) (2025.4.26)
Requirement already satisfied: h11>=0.8 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.24.0)
Requirement already satisfied: six>=1.5 in c:\users\sonku\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)

WARNING: Ignoring invalid distribution ~ip (C:\Users\sonku\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\sonku\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\sonku\AppData\Roaming\Python\Python313\site-packages)